import csv, smtplib

port = 2525 
smtp_server = "smtp.mailtrap.io"
login = "8f6a6d71fd6056" # paste your login generated by Mailtrap
password = "e966a6bc141df8" # paste your password generated by Mailtrap

message = """Subject: Order confirmation
To: {recipient}
From: {sender}

Hi {name}, thanks for your order! We are processing it now and will contact you soon"""
sender = "new@example.com"
with smtplib.SMTP("smtp.mailtrap.io", 2525) as server:
    server.login(login, password)
    with open("C:/xampp/htdocs/product/python-send-email/receiver-list/listContact.csv") as file:
        reader = csv.reader(file)
        next(reader)  # it skips the header row
        for name, email in reader:
            server.sendmail(
               sender,
                email,
                message.format(name=name, recipient=email, sender=sender)
            )
            print(f'Sent to {name}')